# Generated by Django 4.0 on 2021-12-31 21:32

import core.validators
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Date Modified')),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('status', models.CharField(choices=[('unverified', 'Unverified'), ('otp_sent', 'OTP Sent'), ('verified', 'Verified'), ('blocked', 'Blocked')], default='unverified', max_length=16)),
                ('external_id', models.UUIDField(default=uuid.uuid4, unique=True)),
            ],
            options={
                'verbose_name': 'Contact Number',
                'verbose_name_plural': 'Contact Numbers',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. min length: 6, max length: 120', max_length=150, unique=True, validators=[core.validators.UsernameValidator()], verbose_name='username')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('N', 'Rather not say')], max_length=1, null=True, verbose_name='Gender')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='Active')),
                ('inactive_reason', models.CharField(blank=True, choices=[('001', 'Student passed out'), ('002', 'Student transferred to another school'), ('003', 'Debarred for misconduct'), ('004', 'Debarred for fee due'), ('005', 'Debarred for fraud')], max_length=4, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('primary_contact', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='core.contact')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('object', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
